#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$ROOT_DIR"

TAG="${1:-}"
if [[ -z "$TAG" ]]; then
  echo "Usage: $0 <tag>"
  exit 1
fi

# Create source-only archive
ARCHIVE=$(/usr/bin/env bash "$ROOT_DIR/package_release.sh" "$TAG" | awk '{print $2}')

# Create the release (published immediately) with autogenerated notes
if ! gh release view "$TAG" >/dev/null 2>&1; then
  gh release create "$TAG" --generate-notes --latest
fi

# Upload the source archive (clobber if re-running)
gh release upload "$TAG" "$ARCHIVE" --clobber

echo "Release ready: $TAG"
